<?php

// Permisos funcionales: el código es estable y se usa en middleware can: y Blade @can.
return [
    'permissions' => [
        'students.view' => ['Estudiantes', 'Consultar estudiantes y credenciales'],
        'students.create' => ['Estudiantes', 'Registrar estudiantes'],
        'students.edit' => ['Estudiantes', 'Modificar estudiantes'],
        'students.delete' => ['Estudiantes', 'Eliminar estudiantes'],
        'students.import' => ['Estudiantes', 'Importar estudiantes por CSV'],
        'groups.view' => ['Grupos', 'Consultar grupos'],
        'groups.create' => ['Grupos', 'Crear grupos'],
        'groups.edit' => ['Grupos', 'Editar grupos'],
        'groups.delete' => ['Grupos', 'Eliminar grupos'],
        'teachers.view' => ['Docentes', 'Consultar docentes'],
        'teachers.manage' => ['Docentes', 'Administrar docentes y asignaciones'],
        'guardians.view' => ['Tutores', 'Consultar tutores y consentimientos'],
        'guardians.manage' => ['Tutores', 'Administrar tutores y vínculos'],
        'registrations.view' => ['Usuarios', 'Ver solicitudes pendientes'],
        'registrations.manage' => ['Usuarios', 'Aprobar o rechazar registros'],
        'attendance.students.view' => ['Asistencia', 'Consultar asistencia estudiantil'],
        'attendance.students.manage' => ['Asistencia', 'Corregir asistencia estudiantil'],
        'attendance.teachers.view' => ['Asistencia', 'Consultar asistencia docente general'],
        'attendance.teachers.manage' => ['Asistencia', 'Corregir asistencia docente general'],
        'attendance.export' => ['Asistencia', 'Exportar reportes generales'],
        'scan.use' => ['Escaneo', 'Utilizar el kiosco de escaneo'],
        'teacher.attendance.view' => ['Docentes', 'Ver reporte docente personal'],
        'teacher.attendance.manage' => ['Docentes', 'Actualizar reporte docente personal'],
        'teacher.attendance.export' => ['Docentes', 'Exportar reporte docente personal'],
        'parent.portal' => ['Portal', 'Acceder al portal de tutores'],
        'whatsapp.manage' => ['Configuración', 'Administrar la conexión y envíos de WhatsApp'],
        'users.manage' => ['Seguridad', 'Administrar usuarios colaboradores'],
        'roles.manage' => ['Seguridad', 'Administrar roles y permisos'],
    ],
    'system_roles' => [
        'superadmin' => ['Superadministrador', ['*']],
        'admin' => ['Administrador', ['*except_roles']],
        'teacher' => ['Docente', ['scan.use','teacher.attendance.view','teacher.attendance.manage','teacher.attendance.export']],
        'docente' => ['Docente (legado)', ['scan.use','teacher.attendance.view','teacher.attendance.manage','teacher.attendance.export']],
        'parent' => ['Tutor', ['parent.portal']],
        'tutor' => ['Tutor (legado)', ['parent.portal']],
        'student' => ['Estudiante', []],
        'estudiante' => ['Estudiante (legado)', []],
        'supervisor' => ['Supervisor', ['attendance.students.view','attendance.students.manage','attendance.teachers.view','attendance.teachers.manage','attendance.export']],
        'director' => ['Director', ['attendance.students.view','attendance.students.manage','attendance.export']],
        'subdirector' => ['Subdirector', ['attendance.students.view','attendance.students.manage','attendance.export']],
        'orientador' => ['Orientador', ['attendance.students.view','attendance.students.manage','attendance.export']],
        'pedagogo' => ['Pedagogo', ['attendance.students.view','attendance.students.manage','attendance.export']],
        'secretario_escolar' => ['Secretario escolar', ['attendance.students.view','attendance.students.manage','attendance.export']],
        'secretario' => ['Secretario (legado)', ['attendance.students.view','attendance.students.manage','attendance.export']],
    ],
    'starter_roles' => [
        'auxiliar' => ['Auxiliar administrativo', ['students.view','students.create','students.edit','students.import','groups.view','scan.use']],
        'capturista' => ['Capturista', ['students.view','students.create','students.edit','students.import','groups.view']],
    ],
];
